### ISSUE TITLE
Follow OpenTelemetry convention

### ISSUE THREAD

**Issue by gitmalong** [hinohi/rust-opentelemetry-auto-span#1]
According to your docs expanded code example I could not see that sql statements are packed into the `db.statement` field. Would be great if those conventions can be followed upon:

https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/

**Comment by hinohi** [comment]
Thanks for telling me.
I will change the implementation to conform to the official specifications as much as possible.

**Comment by gitmalong** [comment]
There is also an open PR at the `sqlx` crate to implement tracing directly into there. https://github.com/launchbadge/sqlx/pull/2185#issuecomment-1423108995

**Comment by hinohi** [comment]
otel no
